
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.concurrent.ThreadLocalRandom;
import javax.imageio.ImageIO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pthom
 */
public class LeafGenerator extends javax.swing.JFrame {

    /**
     * Creates new form GeneratorWindow
     */
    public LeafGenerator() {
        initComponents();
        this.setTitle("Leaf Generator");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jSeparator3 = new javax.swing.JSeparator();
        popupMenu1 = new java.awt.PopupMenu();
        jFrame1 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        tabsInstructionLabel = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        pinnateTab = new javax.swing.JPanel();
        dimensionsLabel = new javax.swing.JLabel();
        multSignLabel = new javax.swing.JLabel();
        widthField = new javax.swing.JTextField();
        heightField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        midribLabel = new javax.swing.JLabel();
        midribLengthPropLabel = new javax.swing.JLabel();
        midribLengthPropField = new javax.swing.JTextField();
        midribOffsetPropLabel = new javax.swing.JLabel();
        midribOffsetPropField = new javax.swing.JTextField();
        minVarLabel = new javax.swing.JLabel();
        maxVarLabel = new javax.swing.JLabel();
        midribLengthPropLB = new javax.swing.JTextField();
        midribLengthPropRB = new javax.swing.JTextField();
        midribMarginPropLB = new javax.swing.JTextField();
        midribMarginPropRB = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pVLabel = new javax.swing.JLabel();
        maxVarLabelPV = new javax.swing.JLabel();
        minVarLabelPV = new javax.swing.JLabel();
        pVNumVeinsLabel = new javax.swing.JLabel();
        pVNumVeinsField = new javax.swing.JTextField();
        pVNumVeinsLB = new javax.swing.JTextField();
        pVNumVeinsRB = new javax.swing.JTextField();
        pVAngleLabel = new javax.swing.JLabel();
        pVAngleField = new javax.swing.JTextField();
        pVAngleLB = new javax.swing.JTextField();
        pVAngleRB = new javax.swing.JTextField();
        pVVeinLengthsLabel = new javax.swing.JLabel();
        pVVeinLengthsField = new javax.swing.JTextField();
        pVVeinLengthsInstructions = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        genOptsLabel = new javax.swing.JLabel();
        genOptsFileTypeLabel = new javax.swing.JLabel();
        genOptsFileTypeComboBox = new javax.swing.JComboBox<>();
        genOptsPathLabel = new javax.swing.JLabel();
        genOptsPathField = new javax.swing.JTextField();
        genOptsNumLabel = new javax.swing.JLabel();
        genOptsNumSpinner = new javax.swing.JSpinner();
        progressBar = new javax.swing.JProgressBar();
        startButton = new javax.swing.JButton();
        progressLabel = new javax.swing.JLabel();
        pinnateResetButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        ToolMenu = new javax.swing.JMenu();
        setToDefaults = new javax.swing.JMenuItem();

        popupMenu1.setLabel("popupMenu1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabsInstructionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tabsInstructionLabel.setLabelFor(tabs);
        tabsInstructionLabel.setText("Choose a style of leaf to generate on the available tabs.");

        dimensionsLabel.setText("Dimensions");

        multSignLabel.setText("x");

        widthField.setText("1280");
        widthField.setToolTipText("The width of the image that will be generated");
        widthField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                widthFieldActionPerformed(evt);
            }
        });

        heightField.setText("720");
        heightField.setToolTipText("The height of the image that will be generated");

        midribLabel.setText("Midrib");

        midribLengthPropLabel.setText("Length proportion");

        midribLengthPropField.setText("Double between 0.0 and 1.0");
        midribLengthPropField.setToolTipText("Length of the midrib in respect to the width of the image");
        midribLengthPropField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                midribLengthPropFieldActionPerformed(evt);
            }
        });

        midribOffsetPropLabel.setText("Margin proportion");

        midribOffsetPropField.setText("Double between 0.0 and 1.0");
        midribOffsetPropField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                midribOffsetPropFieldActionPerformed(evt);
            }
        });

        minVarLabel.setText("Left Bound");

        maxVarLabel.setText("Right bound");

        midribLengthPropLB.setText("-0.10");
        midribLengthPropLB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                midribLengthPropLBActionPerformed(evt);
            }
        });

        midribLengthPropRB.setText("0.10");
        midribLengthPropRB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                midribLengthPropRBActionPerformed(evt);
            }
        });

        midribMarginPropLB.setText("-0.10");

        midribMarginPropRB.setText("0.10");

        pVLabel.setText("Primary Veins");

        maxVarLabelPV.setText("Right bound");

        minVarLabelPV.setText("Left Bound");

        pVNumVeinsLabel.setText("Num. veins");

        pVNumVeinsField.setEditable(false);
        pVNumVeinsField.setText("Set using bounds");
        pVNumVeinsField.setToolTipText("The number of branching veins from the midrib on one side of the leaf");
        pVNumVeinsField.setEnabled(false);
        pVNumVeinsField.setFocusable(false);
        pVNumVeinsField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pVNumVeinsFieldActionPerformed(evt);
            }
        });

        pVNumVeinsLB.setText("Integer");
        pVNumVeinsLB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pVNumVeinsLBActionPerformed(evt);
            }
        });

        pVNumVeinsRB.setEditable(false);
        pVNumVeinsRB.setText("Integer");
        pVNumVeinsRB.setEnabled(false);
        pVNumVeinsRB.setFocusable(false);
        pVNumVeinsRB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pVNumVeinsRBActionPerformed(evt);
            }
        });

        pVAngleLabel.setText("Angle of veins");

        pVAngleField.setText("Degrees between 0 to 180");
        pVAngleField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pVAngleFieldActionPerformed(evt);
            }
        });

        pVAngleLB.setText("-0.10");

        pVAngleRB.setText("0.10");

        pVVeinLengthsLabel.setText("Vein lengths");

        pVVeinLengthsField.setText("ex. 0.15,0.20,0.20,0.15");
        pVVeinLengthsField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pVVeinLengthsFieldActionPerformed(evt);
            }
        });

        pVVeinLengthsInstructions.setText("Mouseover for instructions");
        pVVeinLengthsInstructions.setToolTipText("<html>Enter numbers that are proportions of the height of the image as the lengths of the veins. Enter them consecuitively and <b>separated by commas</b>.</html>");

        genOptsLabel.setText("Generator Options");

        genOptsFileTypeLabel.setText("File type");

        genOptsFileTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GIF", "PNG", "JPG" }));
        genOptsFileTypeComboBox.setSelectedIndex(1);

        genOptsPathLabel.setText("Output path");

        genOptsPathField.setText(System.getProperty("user.dir"));
        genOptsPathField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                genOptsPathFieldActionPerformed(evt);
            }
        });

        genOptsNumLabel.setText("Number of images to generate");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startButtonActionPerformed(evt);
            }
        });

        progressLabel.setText("Progress");

        pinnateResetButton.setText("Set all values to example values");
        pinnateResetButton.setToolTipText("Resets all fields to example values, current data will be lost!");
        pinnateResetButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                pinnateResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pinnateTabLayout = new javax.swing.GroupLayout(pinnateTab);
        pinnateTab.setLayout(pinnateTabLayout);
        pinnateTabLayout.setHorizontalGroup(
            pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinnateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pinnateTabLayout.createSequentialGroup()
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinnateTabLayout.createSequentialGroup()
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pVNumVeinsLabel)
                                    .addComponent(pVAngleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pVVeinLengthsLabel)
                                    .addComponent(pVLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pinnateTabLayout.createSequentialGroup()
                                        .addComponent(pVVeinLengthsField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pVVeinLengthsInstructions))
                                    .addGroup(pinnateTabLayout.createSequentialGroup()
                                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pinnateTabLayout.createSequentialGroup()
                                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pVNumVeinsField)
                                                    .addComponent(pVAngleField))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(pVNumVeinsLB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pVAngleLB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinnateTabLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(minVarLabelPV)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(maxVarLabelPV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pVNumVeinsRB)
                                            .addComponent(pVAngleRB)))))
                            .addComponent(jSeparator4)
                            .addGroup(pinnateTabLayout.createSequentialGroup()
                                .addComponent(genOptsPathLabel)
                                .addGap(18, 18, 18)
                                .addComponent(genOptsPathField)
                                .addGap(18, 18, 18)
                                .addComponent(genOptsFileTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genOptsFileTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinnateTabLayout.createSequentialGroup()
                                .addComponent(progressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startButton))
                            .addGroup(pinnateTabLayout.createSequentialGroup()
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(midribLengthPropLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(midribOffsetPropLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(midribLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(midribOffsetPropField)
                                    .addComponent(midribLengthPropField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(minVarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(midribLengthPropLB)
                                    .addComponent(midribMarginPropLB))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maxVarLabel)
                                    .addComponent(midribLengthPropRB)
                                    .addComponent(midribMarginPropRB)))
                            .addComponent(jSeparator1)
                            .addGroup(pinnateTabLayout.createSequentialGroup()
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pinnateTabLayout.createSequentialGroup()
                                        .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(multSignLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(genOptsLabel)
                                    .addComponent(dimensionsLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(pinnateTabLayout.createSequentialGroup()
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pinnateTabLayout.createSequentialGroup()
                                .addComponent(genOptsNumLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(genOptsNumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pinnateResetButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pinnateTabLayout.setVerticalGroup(
            pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinnateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dimensionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pinnateTabLayout.createSequentialGroup()
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(widthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(heightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multSignLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinnateTabLayout.createSequentialGroup()
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pinnateTabLayout.createSequentialGroup()
                                        .addComponent(maxVarLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(midribLengthPropRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(midribLengthPropField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinnateTabLayout.createSequentialGroup()
                                        .addComponent(midribLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(midribLengthPropLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(midribMarginPropRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(midribOffsetPropField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(midribOffsetPropLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinnateTabLayout.createSequentialGroup()
                                .addComponent(minVarLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(midribLengthPropLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(midribMarginPropLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pVNumVeinsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinnateTabLayout.createSequentialGroup()
                                .addComponent(pVLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pVNumVeinsLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pVAngleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pVAngleLabel)))
                    .addGroup(pinnateTabLayout.createSequentialGroup()
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxVarLabelPV)
                            .addComponent(minVarLabelPV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pVNumVeinsRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pVNumVeinsLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pVAngleRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pVAngleLB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pVVeinLengthsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pVVeinLengthsLabel)
                    .addComponent(pVVeinLengthsInstructions))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genOptsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genOptsPathLabel)
                    .addComponent(genOptsPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genOptsFileTypeLabel)
                    .addComponent(genOptsFileTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genOptsNumLabel)
                    .addComponent(genOptsNumSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinnateResetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(pinnateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(progressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pinnateTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {midribLengthPropField, midribOffsetPropField});

        pinnateTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pVAngleField, pVNumVeinsField, pVVeinLengthsField});

        tabs.addTab("Pinnately Veined", pinnateTab);
        tabs.addTab("tab2", jTabbedPane1);

        FileMenu.setText("File");
        jMenuBar2.add(FileMenu);

        EditMenu.setText("Edit");
        jMenuBar2.add(EditMenu);

        ToolMenu.setText("Tools");

        setToDefaults.setText("Set all fields to example values");
        setToDefaults.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                setToDefaultsActionPerformed(evt);
            }
        });
        ToolMenu.add(setToDefaults);

        jMenuBar2.add(ToolMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabsInstructionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabsInstructionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genOptsPathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genOptsPathFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genOptsPathFieldActionPerformed

    private void pVVeinLengthsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pVVeinLengthsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pVVeinLengthsFieldActionPerformed

    private void pVAngleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pVAngleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pVAngleFieldActionPerformed

    private void pVNumVeinsRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pVNumVeinsRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pVNumVeinsRBActionPerformed

    private void pVNumVeinsLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pVNumVeinsLBActionPerformed
        pVNumVeinsRB.setText(pVNumVeinsLB.getText());
    }//GEN-LAST:event_pVNumVeinsLBActionPerformed

    private void pVNumVeinsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pVNumVeinsFieldActionPerformed
        pVNumVeinsLB.setText(pVNumVeinsField.getText());
    }//GEN-LAST:event_pVNumVeinsFieldActionPerformed

    private void midribLengthPropRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midribLengthPropRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midribLengthPropRBActionPerformed

    private void midribLengthPropLBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midribLengthPropLBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midribLengthPropLBActionPerformed

    private void midribOffsetPropFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midribOffsetPropFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midribOffsetPropFieldActionPerformed

    private void widthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthFieldActionPerformed

    private void midribLengthPropFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_midribLengthPropFieldActionPerformed
    {//GEN-HEADEREND:event_midribLengthPropFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midribLengthPropFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startButtonActionPerformed
    {//GEN-HEADEREND:event_startButtonActionPerformed
        // initialize variables to be gotten from fields
        // dimensions
        int width, height;
        // midrib
        double midribLenProp, midribOffsetProp;
        double[] midribLenPropBounds = new double[2];
        double[] midribOffsetPropBounds = new double[2];
        
        // primary veins
        String[] pVLenStrs = pVVeinLengthsField.getText().split(",");
        double[] pVLengths = new double[pVLenStrs.length];
        double[] pVParameters = new double[2 + pVLenStrs.length];
        double[] pVAngleBounds = new double[2];
        double[] pVLengthBounds = {0.9, 1.1};
        
        // get values from fields
        width = Integer.parseInt(widthField.getText());
        height = Integer.parseInt(heightField.getText());
        
        midribLenProp = Double.parseDouble(midribLengthPropField.getText());
        midribLenPropBounds[0] = 1.0 + Double.parseDouble(midribLengthPropLB.getText());
        midribLenPropBounds[1] = 1.0 + Double.parseDouble(midribLengthPropRB.getText());
        
        midribOffsetProp = Double.parseDouble(midribOffsetPropField.getText());
        midribOffsetPropBounds[0] = 1.0 + Double.parseDouble(midribMarginPropLB.getText());
        midribOffsetPropBounds[1] = 1.0 + Double.parseDouble(midribMarginPropRB.getText());
        
        // copy strings to doubles in arrays
        for (int i = 0; i < pVLenStrs.length; i++)
        {
            pVLengths[i] = Double.parseDouble(pVLenStrs[i]);
        } // end for loop
        
        pVParameters[0] = Double.parseDouble(pVNumVeinsLB.getText());
        pVParameters[1] = Double.parseDouble(pVAngleField.getText());
        
        for (int i = 2; i < pVParameters.length; i++)
        {
            pVParameters[i] = pVLengths[i-2];
        } // end for loop
        
        pVAngleBounds[0] = 1.0 + Double.parseDouble(pVAngleLB.getText());
        pVAngleBounds[1] = 1.0 + Double.parseDouble(pVAngleRB.getText());
        
        
        for (int i = 0; i < (int) genOptsNumSpinner.getValue(); i++)
        {
            // generate random numbers between bounds
            double midribLenPropMult = ThreadLocalRandom.current().nextDouble(
                    midribLenPropBounds[0],
                    midribLenPropBounds[1]
            );
            double midribOffsetPropMult = ThreadLocalRandom.current().nextDouble(
                    midribOffsetPropBounds[0],
                    midribOffsetPropBounds[1]
            );
            double pVAngleMult = ThreadLocalRandom.current().nextDouble(
                    pVAngleBounds[0],
                    pVAngleBounds[1]
            );
            
            // multiply parameters by random values
            pVParameters[1] *= pVAngleMult;
            
            for (int j = 2; j < pVParameters.length; j++)
            {
                pVParameters[j] *= ThreadLocalRandom.current().nextDouble(
                        pVLengthBounds[0],
                        pVLengthBounds[1]
                );
            } // end for loop

            LeafArrayGenerator arrayGen = new LeafArrayGenerator(
                            width,		// width 
                            height,		// height
                            midribLenProp * midribLenPropMult, 	
                                                // midrib length proportion
                            1,                  // midrib actual length (unused)
                            midribOffsetProp * midribOffsetPropMult,	
                                                // midrib start offset proportion
                            "pinnate",
                            pVParameters
                            );


            try 
            {
                // retrieve image
                BufferedImage bi = arrayGen.createBufferedImage();
                File outputFile;
                outputFile = new File("saved" + (i+1) + ".png");
                ImageIO.write(
                        bi, 
                        (String) genOptsFileTypeComboBox.getSelectedItem(), 
                        outputFile
                );
            } // end try
            catch (IOException e)
            {
                e.printStackTrace();
            } // end catch
        } // end for loop
    }//GEN-LAST:event_startButtonActionPerformed

    private void pinnateResetButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_pinnateResetButtonActionPerformed
    {//GEN-HEADEREND:event_pinnateResetButtonActionPerformed
        // set all the fields to default values
        // define default values in final variables
        // dimensions
        int width     = 1280;
        int height    = 720;
        // midrib
        double midribLenProp            = 0.7;
        double midribOffsetProp         = 0.1;
        double[] midribLenPropBounds    = {-0.1, 0.1};
        double[] midribOffsetPropBounds = {-0.1, 0.1};
        
        // primary veins
        String pVLengths = "0.15,0.17,0.21,0.18";
        double pVNumber = 4.0;
        double pVAngle = 45.0;
        double[] pVAngleBounds  = {-0.1, 0.1};
        double[] pVLengthBounds = {-0.1, 0.1};
        
        // set fields
        widthField.setText(Integer.toString(width));
        heightField.setText(Integer.toString(height));
        
        midribLengthPropField.setText(Double.toString(midribLenProp));
        midribLengthPropLB.setText(Double.toString(midribLenPropBounds[0]));
        midribLengthPropRB.setText(Double.toString(midribLenPropBounds[1]));
        
        midribOffsetPropField.setText(Double.toString(midribOffsetProp));
        midribMarginPropLB.setText(Double.toString(midribOffsetPropBounds[0]));
        midribMarginPropRB.setText(Double.toString(midribOffsetPropBounds[1]));
        
        pVAngleField.setText(Double.toString(pVAngle));
        pVAngleLB.setText(Double.toString(pVAngleBounds[0]));
        pVAngleRB.setText(Double.toString(pVAngleBounds[1]));
        
        pVNumVeinsLB.setText(Double.toString(pVNumber));
        pVVeinLengthsField.setText(pVLengths);
        genOptsNumSpinner.setValue((int) 1);
        
    }//GEN-LAST:event_pinnateResetButtonActionPerformed

    private void setToDefaultsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_setToDefaultsActionPerformed
    {//GEN-HEADEREND:event_setToDefaultsActionPerformed
        if (tabs.getSelectedComponent() == pinnateTab)
        {
            pinnateResetButtonActionPerformed(null);
        } // end if the selected tab is the pinnate tab
    }//GEN-LAST:event_setToDefaultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeafJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeafJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu ToolMenu;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JComboBox<String> genOptsFileTypeComboBox;
    private javax.swing.JLabel genOptsFileTypeLabel;
    private javax.swing.JLabel genOptsLabel;
    private javax.swing.JLabel genOptsNumLabel;
    private javax.swing.JSpinner genOptsNumSpinner;
    private javax.swing.JTextField genOptsPathField;
    private javax.swing.JLabel genOptsPathLabel;
    private javax.swing.JTextField heightField;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel maxVarLabel;
    private javax.swing.JLabel maxVarLabelPV;
    private javax.swing.JLabel midribLabel;
    private javax.swing.JTextField midribLengthPropField;
    private javax.swing.JTextField midribLengthPropLB;
    private javax.swing.JLabel midribLengthPropLabel;
    private javax.swing.JTextField midribLengthPropRB;
    private javax.swing.JTextField midribMarginPropLB;
    private javax.swing.JTextField midribMarginPropRB;
    private javax.swing.JTextField midribOffsetPropField;
    private javax.swing.JLabel midribOffsetPropLabel;
    private javax.swing.JLabel minVarLabel;
    private javax.swing.JLabel minVarLabelPV;
    private javax.swing.JLabel multSignLabel;
    private javax.swing.JTextField pVAngleField;
    private javax.swing.JTextField pVAngleLB;
    private javax.swing.JLabel pVAngleLabel;
    private javax.swing.JTextField pVAngleRB;
    private javax.swing.JLabel pVLabel;
    private javax.swing.JTextField pVNumVeinsField;
    private javax.swing.JTextField pVNumVeinsLB;
    private javax.swing.JLabel pVNumVeinsLabel;
    private javax.swing.JTextField pVNumVeinsRB;
    private javax.swing.JTextField pVVeinLengthsField;
    private javax.swing.JLabel pVVeinLengthsInstructions;
    private javax.swing.JLabel pVVeinLengthsLabel;
    private javax.swing.JButton pinnateResetButton;
    private javax.swing.JPanel pinnateTab;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JMenuItem setToDefaults;
    private javax.swing.JButton startButton;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JLabel tabsInstructionLabel;
    private javax.swing.JTextField widthField;
    // End of variables declaration//GEN-END:variables
}
